const money=new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0});
const def={presale:{price:600,count:120,fee:40},door:{price:700,count:20},venues:[{threshold:0,presalePer:400,doorPer:500},{threshold:120,presalePer:460,doorPer:560}],subsidies:[{threshold:0,amount:10000},{threshold:120,amount:20000}],costs:[{name:'海外藝人演出費',amount:25000},{name:'機票／住宿',amount:12000},{name:'國內 DJ／演出費',amount:8000},{name:'場地／器材／行政',amount:13000}]};
let state=structuredClone(def),chart;const $=s=>document.querySelector(s),n=v=>Number(v)||0;
function tier(arr,total){let hit=null;for(const x of [...arr].sort((a,b)=>a.threshold-b.threshold))if(total>=x.threshold)hit=x;return hit}
function calc(pre=state.presale.count,door=state.door.count){pre=Math.max(0,n(pre));door=Math.max(0,n(door));const total=pre+door;const gross=pre*n(state.presale.price)+door*n(state.door.price);const fees=pre*n(state.presale.fee);const vt=tier(state.venues,total);const venue=vt?pre*n(vt.presalePer)+door*n(vt.doorPer):gross-fees;const st=tier(state.subsidies,total);const sub=st?n(st.amount):0;const cost=state.costs.reduce((a,x)=>a+n(x.amount),0);const net=venue+sub-cost;const income=venue+sub;return{pre,door,total,gross,fees,vt,venue,st,sub,cost,net,margin:income?net/income:0}}
function render(){
  $('#presaleFields').innerHTML=`<div class="row ticket"><label>預售票價<input type="number" data-pre="price" value="${state.presale.price}"></label><label>預售張數<input type="number" data-pre="count" value="${state.presale.count}"></label><label>平台每張票抽<input type="number" data-pre="fee" value="${state.presale.fee}"></label></div>`;
  $('#doorFields').innerHTML=`<div class="row ticket"><label>現場票價<input type="number" data-door="price" value="${state.door.price}"></label><label>現場票張數<input type="number" data-door="count" value="${state.door.count}"></label></div>`;
  $('#venues').innerHTML=state.venues.map((x,i)=>`<div class="row venue3"><label>達到／超過總人數<input type="number" data-v="${i}" data-k="threshold" value="${x.threshold}"></label><label>預售每張主辦實拿<input type="number" data-v="${i}" data-k="presalePer" value="${x.presalePer}"></label><label>現場每張主辦實拿<input type="number" data-v="${i}" data-k="doorPer" value="${x.doorPer}"></label><button class="remove" data-rv="${i}">×</button></div>`).join('');
  $('#subsidies').innerHTML=state.subsidies.map((x,i)=>`<div class="row tier"><label>達到／超過總人數<input type="number" data-s="${i}" data-k="threshold" value="${x.threshold}"></label><label>補助金額<input type="number" data-s="${i}" data-k="amount" value="${x.amount}"></label><button class="remove" data-rs="${i}">×</button></div>`).join('');
  $('#costs').innerHTML=state.costs.map((x,i)=>`<div class="row costrow"><label>成本項目<input data-c="${i}" data-k="name" value="${x.name}"></label><label>金額<input type="number" data-c="${i}" data-k="amount" value="${x.amount}"></label><button class="remove" data-rc="${i}">×</button></div>`).join('');update();draw()}
function breakeven(){const cap=n($('#cap').value),door=n(state.door.count);for(let pre=0;pre<=Math.max(0,cap-door);pre++)if(calc(pre,door).net>=0)return{pre,total:pre+door};return null}
function update(){const r=calc();$('#shownCap').textContent=n($('#cap').value);$('#shownNow').textContent=r.total;$('#title').textContent=$('#name').value||'未命名活動';$('#preRevenue').textContent=money.format(r.pre*n(state.presale.price));$('#doorRevenue').textContent=money.format(r.door*n(state.door.price));$('#gross').textContent=money.format(r.gross);$('#fees').textContent=money.format(r.fees);$('#venueRev').textContent=money.format(r.venue);$('#subsidy').textContent=money.format(r.sub);$('#cost').textContent=money.format(r.cost);$('#profit').textContent=money.format(r.net);$('#profit').style.color=r.net>=0?'#86efac':'#fca5a5';$('#margin').textContent='淨利率 '+(r.margin*100).toFixed(1)+'%';$('#venueTier').textContent=r.vt?`${r.vt.threshold}+ 人｜預售 ${money.format(r.vt.presalePer)}／張｜現場 ${money.format(r.vt.doorPer)}／張`:'—';$('#subTier').textContent=r.st?`${r.st.threshold}+ 人 → ${money.format(r.st.amount)}`:'—';const b=breakeven();$('#be').textContent=b?`預售 ${b.pre} 張／總人數 ${b.total}`:'容量內未回本';$('#totalPeople').textContent=r.total+' 人'}
function draw(){const cap=n($('#cap').value),door=n(state.door.count),maxPre=Math.max(0,cap-door),step=Math.max(5,Math.round(maxPre/16)),ls=[],ds=[];for(let pre=0;pre<=maxPre;pre+=step){ls.push(pre);ds.push(calc(pre,door).net)}if(ls.at(-1)!==maxPre){ls.push(maxPre);ds.push(calc(maxPre,door).net)}chart?.destroy();chart=new Chart($('#chart'),{type:'line',data:{labels:ls,datasets:[{data:ds,borderWidth:2,tension:.25,pointRadius:2}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{callback:v=>money.format(v)}},x:{title:{display:true,text:'預售票張數（現場票固定）'}}}}})}
document.addEventListener('input',e=>{const t=e.target,k=t.dataset.k;if(t.dataset.pre!==undefined)state.presale[t.dataset.pre]=n(t.value);if(t.dataset.door!==undefined)state.door[t.dataset.door]=n(t.value);if(t.dataset.v!==undefined)state.venues[n(t.dataset.v)][k]=n(t.value);if(t.dataset.s!==undefined)state.subsidies[n(t.dataset.s)][k]=n(t.value);if(t.dataset.c!==undefined)state.costs[n(t.dataset.c)][k]=k==='name'?t.value:n(t.value);update();draw()});
document.addEventListener('click',e=>{const b=e.target;if(b.id==='addVenue')state.venues.push({threshold:0,presalePer:0,doorPer:0});if(b.id==='addSubsidy')state.subsidies.push({threshold:0,amount:0});if(b.id==='addCost')state.costs.push({name:'新成本',amount:0});if(b.dataset.rv!==undefined&&state.venues.length>1)state.venues.splice(n(b.dataset.rv),1);if(b.dataset.rs!==undefined&&state.subsidies.length>1)state.subsidies.splice(n(b.dataset.rs),1);if(b.dataset.rc!==undefined)state.costs.splice(n(b.dataset.rc),1);if(b.id==='reset'){state=structuredClone(def);$('#name').value='Soul Out Vol.11';$('#date').value='2026-09-19';$('#cap').value=160}render()});render();