const money=new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0});
const def={presale:{price:600,fee:40,tiers:[{threshold:0,per:400},{threshold:120,per:460}]},door:{price:700,count:20,tiers:[{threshold:0,per:500},{threshold:120,per:560}]},subsidies:[{threshold:0,amount:10000},{threshold:120,amount:20000}],costs:[{name:'海外藝人演出費',amount:25000},{name:'機票／住宿',amount:12000},{name:'國內 DJ／演出費',amount:8000},{name:'場地／器材／行政',amount:13000}],step:10};
let state=structuredClone(def);const $=s=>document.querySelector(s),n=v=>Number(v)||0;
function tier(arr,count){let hit=null;for(const x of [...arr].sort((a,b)=>a.threshold-b.threshold))if(count>=x.threshold)hit=x;return hit}
function calc(pre){pre=Math.max(0,n(pre));const door=Math.max(0,n(state.door.count));const total=pre+door;const grossPre=pre*n(state.presale.price),grossDoor=door*n(state.door.price),gross=grossPre+grossDoor,fees=pre*n(state.presale.fee);const preTier=tier(state.presale.tiers,total),doorTier=tier(state.door.tiers,total);const preVenue=preTier?pre*n(preTier.per):grossPre;const doorVenue=doorTier?door*n(doorTier.per):grossDoor;const venueBeforeFees=preVenue+doorVenue;const st=tier(state.subsidies,total),sub=st?n(st.amount):0;const organizerIncome=venueBeforeFees-fees+sub;const cost=state.costs.reduce((a,x)=>a+n(x.amount),0);const net=organizerIncome-cost;return{pre,door,total,gross,grossPre,grossDoor,fees,preTier,doorTier,preVenue,doorVenue,venueBeforeFees,st,sub,organizerIncome,cost,net}}
function tierRows(kind){return state[kind].tiers.map((x,i)=>`<div class="row tier"><label>達到／超過總人數<input type="number" data-${kind}-tier="${i}" data-k="threshold" value="${x.threshold}"></label><label>主辦每張實拿<input type="number" data-${kind}-tier="${i}" data-k="per" value="${x.per}"></label><button class="remove" data-remove-${kind}-tier="${i}">×</button></div>`).join('')}
function renderInputs(){
 $('#presaleFields').innerHTML=`<div class="row ticket"><label>預售票價<input type="number" data-pre="price" value="${state.presale.price}"></label><label>平台每張票抽<input type="number" data-pre="fee" value="${state.presale.fee}"></label><label>預售試算間隔<input type="number" id="stepInput" min="1" value="${state.step}"></label></div><div class="title sub"><div><h3>預售票｜場地拆票</h3><p>級距門檻看預售＋現場總人數，金額只套用到預售票。</p></div><button id="addPresaleTier">＋新增級距</button></div><div id="presaleTiers">${tierRows('presale')}</div>`;
 $('#doorFields').innerHTML=`<div class="row ticket"><label>現場票價<input type="number" data-door="price" value="${state.door.price}"></label><label>現場票張數<input type="number" data-door="count" value="${state.door.count}"></label></div><div class="title sub"><div><h3>現場票｜場地拆票</h3><p>級距門檻同樣看總人數，金額只套用到現場票。</p></div><button id="addDoorTier">＋新增級距</button></div><div id="doorTiers">${tierRows('door')}</div>`;
 $('#subsidies').innerHTML=state.subsidies.map((x,i)=>`<div class="row tier"><label>達到／超過總人數<input type="number" data-s="${i}" data-k="threshold" value="${x.threshold}"></label><label>補助金額<input type="number" data-s="${i}" data-k="amount" value="${x.amount}"></label><button class="remove" data-rs="${i}">×</button></div>`).join('');
 $('#costs').innerHTML=state.costs.map((x,i)=>`<div class="row costrow"><label>成本項目<input data-c="${i}" data-k="name" value="${x.name}"></label><label>金額<input type="number" data-c="${i}" data-k="amount" value="${x.amount}"></label><button class="remove" data-rc="${i}">×</button></div>`).join('')
}
function buildPresalePoints(){const cap=Math.max(0,n($('#cap').value)),door=Math.max(0,n(state.door.count)),maxPre=Math.max(0,cap-door),step=Math.max(1,n(state.step));const pts=[];for(let p=0;p<=maxPre;p+=step)pts.push(p);if(pts.at(-1)!==maxPre)pts.push(maxPre);return pts}
function renderTable(){const pts=buildPresalePoints(),rows=pts.map(calc);const firstProfit=rows.find(r=>r.net>=0);$('#breakEvenSummary').textContent=firstProfit?`預售 ${firstProfit.pre} 張／總人數 ${firstProfit.total}`:'容量內未回本';$('#doorSummary').textContent=`${state.door.count} 張`;$('#costSummary').textContent=money.format(rows[0]?.cost||0);$('#scenarioBody').innerHTML=rows.map(r=>`<tr class="${firstProfit&&r.pre===firstProfit.pre?'breakeven-row':''}"><td>${r.pre}</td><td>${r.door}</td><td>${r.total}</td><td>${money.format(r.fees)}</td><td>${money.format(r.preVenue)}</td><td>${money.format(r.doorVenue)}</td><td>${money.format(r.sub)}</td><td>${money.format(r.organizerIncome)}</td><td>${money.format(r.cost)}</td><td class="${r.net>=0?'positive':'negative'}">${money.format(r.net)}</td></tr>`).join('')}
function render(){renderInputs();renderTable()}
document.addEventListener('input',e=>{const t=e.target,k=t.dataset.k;if(t.dataset.pre!==undefined)state.presale[t.dataset.pre]=n(t.value);if(t.dataset.door!==undefined)state.door[t.dataset.door]=n(t.value);if(t.id==='stepInput')state.step=Math.max(1,n(t.value));if(t.dataset.presaleTier!==undefined)state.presale.tiers[n(t.dataset.presaleTier)][k]=n(t.value);if(t.dataset.doorTier!==undefined)state.door.tiers[n(t.dataset.doorTier)][k]=n(t.value);if(t.dataset.s!==undefined)state.subsidies[n(t.dataset.s)][k]=n(t.value);if(t.dataset.c!==undefined)state.costs[n(t.dataset.c)][k]=k==='name'?t.value:n(t.value);renderTable()});
document.addEventListener('click',e=>{const b=e.target;if(b.id==='addPresaleTier')state.presale.tiers.push({threshold:0,per:0});if(b.id==='addDoorTier')state.door.tiers.push({threshold:0,per:0});if(b.id==='addSubsidy')state.subsidies.push({threshold:0,amount:0});if(b.id==='addCost')state.costs.push({name:'新成本',amount:0});if(b.dataset.removePresaleTier!==undefined&&state.presale.tiers.length>1)state.presale.tiers.splice(n(b.dataset.removePresaleTier),1);if(b.dataset.removeDoorTier!==undefined&&state.door.tiers.length>1)state.door.tiers.splice(n(b.dataset.removeDoorTier),1);if(b.dataset.rs!==undefined&&state.subsidies.length>1)state.subsidies.splice(n(b.dataset.rs),1);if(b.dataset.rc!==undefined)state.costs.splice(n(b.dataset.rc),1);if(b.id==='reset'){state=structuredClone(def);$('#name').value='Soul Out Vol.11';$('#date').value='2026-09-19';$('#cap').value=160}if(b.id==='addPresaleTier'||b.id==='addDoorTier'||b.id==='addSubsidy'||b.id==='addCost'||b.dataset.removePresaleTier!==undefined||b.dataset.removeDoorTier!==undefined||b.dataset.rs!==undefined||b.dataset.rc!==undefined||b.id==='reset')render()});render();